baseURL = "https://est.netlify.com/"
languageCode = "en-us"
title = "Ericsson Software Technology"
disableKinds = ["sitemap"]

[params]
  description = "Fostering open source, collaborative technology"

[outputs]
  home = [ "HTML", "CSS" ]

[taxonomies]
  tag = ""
  category = ""
