baseURL = "https://esttech.github.io/"
languageCode = "en-us"
title = "Ericsson Software Technology"
disableKinds = ["sitemap"]

[outputs]
  home = [ "HTML", "CSS" ]

[taxonomies]
  tag = ""
  category = ""
